import pygame
from pygame import Color

# Window Setting
WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 1280*9//16
WINDOW = pygame.display.set_mode((WINDOW_WIDTH, WINDOW_HEIGHT))

# Constants
## Calendar Box
CALENDAR_BORDER_RATIO = 0.04
CALENDAR_CROP_RATIO = 0.7
CALENDAR_WIDTH = int(WINDOW_WIDTH*(1-2*CALENDAR_BORDER_RATIO))
CALENDAR_HEIGHT = 800
CALENDAR_TOP = CALENDAR_BORDER_RATIO*WINDOW_HEIGHT
CALENDAR_LEFT = CALENDAR_BORDER_RATIO*WINDOW_WIDTH
CALENDAR_BOTTOM_FULL = WINDOW_HEIGHT-CALENDAR_TOP
CALENDAR_BOTTOM_CROPPED = CALENDAR_TOP + int(1-CALENDAR_CROP_RATIO)*WINDOW_HEIGHT
CALENDAR_CORNER_RADIUS = int(0.013*CALENDAR_WIDTH)



# Colors
CALENDAR_BACKGROUND = Color(245,245,250)
MAIN_BACKGROUND = Color(220,225,235)


class CalendarBox(object):
    def __init__(self):

        self.rect = pygame.Rect(CALENDAR_LEFT, CALENDAR_TOP, CALENDAR_WIDTH, CALENDAR_BOTTOM_FULL-CALENDAR_TOP)
        self.color = CALENDAR_BACKGROUND

    def render(self):
        pygame.draw.rect(WINDOW, self.color, self.rect, border_radius=CALENDAR_CORNER_RADIUS)

